import type { SiteLocale } from "./locale";

export const siteCopy = {
  zh: {
    templates: "模板库",
    categories: "分类",
    docs: "使用说明",
    login: "登录",
    signup: "注册",
    share: "分享模板",
    browseAll: "浏览全部",
    featured: "精选模板",
    allTemplates: "全部模板",
    searchPlaceholder: "搜索模板、分类或视觉风格",
    search: "搜索",
    popular: "热门排序",
    newest: "最新分享",
    name: "名称排序",
    views: "浏览",
    likes: "点赞",
    preview: "查看预览",
    openPreview: "在新标签页打开",
    copyForAi: "复制给 AI",
    copied: "迁移指令已复制",
    manualCopy: "请手动复制下面的完整内容",
    draft: "开发预览",
    contract: "模板契约",
    official: "官方",
    partner: "合作作者",
    community: "社区作者",
    framework: "框架",
    library: "组件库",
    platform: "平台",
    runtime: "运行宿主",
    compatibility: "兼容范围",
    components: "组件清单",
    skeletons: "页面骨架",
    artifact: "模板包",
    version: "固定版本",
    updatedAt: "更新时间",
    noResults: "没有匹配的模板",
    noResultsBody: "换一个关键词或筛选条件试试。",
    resetFilters: "清除筛选",
    categoryOverview: "全部模板分类",
    categoryOverviewBody: "按产品用途浏览公开模板，每个分类都用代表页面展示视觉方向。",
    categoriesCount: "个分类",
    showcasesCount: "个 Showcase",
    categoryEmpty: "这个分类正在整理",
    categoryEmptyBody: "公开模板通过审核后会出现在这里。",
    details: "模板详情",
    latestStable: "最新稳定实现",
    internalFixture: "当前为内部开发 fixture，尚未进入公开发布。",
    relatedCategories: "适用分类",
    showcase: "Showcase",
    componentLab: "组件实验室",
    theme: "网站主题",
    light: "浅色",
    dark: "深色",
    language: "切换语言",
    close: "关闭",
    unavailableTitle: "入口已保留",
    unavailableBody: "账号、投稿和持久化互动会通过能力开关逐步开放。当前入口不会发送真实请求。",
    useWithAi: "把模板交给 AI",
    useWithAiBody: "复制固定版本迁移指令，让 AI 下载、校验并迁移真实模板源码。"
  },
  en: {
    templates: "Templates",
    categories: "Categories",
    docs: "Use with AI",
    login: "Log in",
    signup: "Sign up",
    share: "Share template",
    browseAll: "Browse all",
    featured: "Featured templates",
    allTemplates: "All templates",
    searchPlaceholder: "Search templates, categories, or visual styles",
    search: "Search",
    popular: "Trending",
    newest: "Newest",
    name: "Name",
    views: "views",
    likes: "likes",
    preview: "Open preview",
    openPreview: "Open in new tab",
    copyForAi: "Copy for AI",
    copied: "Migration instruction copied",
    manualCopy: "Copy the complete text manually",
    draft: "Development preview",
    contract: "Template contract",
    official: "Official",
    partner: "Partner",
    community: "Community",
    framework: "Framework",
    library: "Component library",
    platform: "Platform",
    runtime: "Runtime",
    compatibility: "Compatibility",
    components: "Components",
    skeletons: "Page skeletons",
    artifact: "Template package",
    version: "Fixed version",
    updatedAt: "Updated",
    noResults: "No matching templates",
    noResultsBody: "Try another keyword or filter.",
    resetFilters: "Clear filters",
    categoryOverview: "All template categories",
    categoryOverviewBody: "Browse public templates by product use case and visual direction.",
    categoriesCount: "categories",
    showcasesCount: "showcases",
    categoryEmpty: "This category is being curated",
    categoryEmptyBody: "Approved public templates will appear here.",
    details: "Template details",
    latestStable: "Latest stable implementation",
    internalFixture: "This is an internal development fixture and is not publicly released.",
    relatedCategories: "Use cases",
    showcase: "Showcase",
    componentLab: "Component lab",
    theme: "Site theme",
    light: "Light",
    dark: "Dark",
    language: "Change language",
    close: "Close",
    unavailableTitle: "Entry reserved",
    unavailableBody: "Accounts, submissions, and persistent interactions will open behind explicit capability flags. This entry sends no real request yet.",
    useWithAi: "Use with AI",
    useWithAiBody: "Copy a fixed-version migration instruction so AI can download, verify, and migrate the real template source."
  }
} as const;

export type SiteCopy = (typeof siteCopy)[SiteLocale];

export function getSiteCopy(locale: SiteLocale): SiteCopy {
  return siteCopy[locale];
}
