// UIDevTpl 主站原型数据：分类、模板和双语文案。
// 这份文件只放内容数据，渲染和交互逻辑在 app.js。两个文件都以经典脚本加载，
// data.js 先于 app.js，所以这里的顶层 const 在 app.js 里可以直接读到。

const categories = [
  {
    id: "apps",
    icon: "A",
    name: { zh: "应用与游戏", en: "Apps & Games" },
    description: { zh: "工作流、创作工具与互动体验", en: "Workflows, creative tools, and interactive products" }
  },
  {
    id: "landing",
    icon: "L",
    name: { zh: "营销与落地页", en: "Landing Pages" },
    description: { zh: "产品发布、品牌表达与转化页面", en: "Launches, brand stories, and conversion pages" }
  },
  {
    id: "dashboards",
    icon: "D",
    name: { zh: "数据看板", en: "Dashboards" },
    description: { zh: "运营、分析与高密度信息界面", en: "Operations, analytics, and dense information" }
  },
  {
    id: "components",
    icon: "C",
    name: { zh: "组件与交互", en: "Components" },
    description: { zh: "表单、状态与可复用交互组合", en: "Forms, states, and reusable patterns" }
  },
  {
    id: "auth",
    icon: "S",
    name: { zh: "登录与注册", en: "Login & Sign Up" },
    description: { zh: "登录、注册与账号恢复流程", en: "Sign in, registration, and recovery flows" }
  },
  {
    id: "content",
    icon: "N",
    name: { zh: "内容与作品集", en: "Content & Portfolios" },
    description: { zh: "博客、知识内容与个人作品展示", en: "Editorial content, knowledge, and portfolios" }
  }
];

// 模板字段说明：
// route 对应设计文档里的固定路由 /templates/:platform/:framework/:library/:slug
// check 列里的 buildTool / packageManager / artifactSize / sha256 / license / compatibility
// 只用于原型展示，正式站会从固定产物里读真实值。
const templates = [
  {
    id: "quiet-workspace",
    slug: "quiet-grid",
    route: "web/react/shadcn/quiet-grid",
    name: { zh: "Quiet Grid Workspace", en: "Quiet Grid Workspace" },
    family: "Quiet Grid",
    type: "workspace",
    accent: "lime",
    author: { name: { zh: "UIDevTpl 团队", en: "UIDevTpl Studio" }, initials: "UI" },
    summary: {
      zh: "安静、精确的工作界面，适合复杂任务和高密度信息。",
      en: "A calm, precise workspace for complex tasks and dense information."
    },
    categories: ["apps", "dashboards", "components"],
    platform: "Web",
    framework: "react",
    frameworkLabel: "React",
    library: "shadcn/ui",
    latestVersion: "0.1.0",
    pinnedVersion: "0.1.0-preview",
    views: 12800,
    likes: 936,
    updated: 4,
    tags: ["Web", "React", "shadcn/ui", "Light"],
    components: ["Button", "Badge", "Tabs", "DataTable", "Sidebar", "Dialog"],
    tokens: [
      ["Canvas", "neutral / 50"],
      ["Primary", "signal / lime"],
      ["Radius", "8px max"],
      ["Type", "Noto Sans"]
    ],
    buildTool: "Vite",
    packageManager: "pnpm",
    artifactSize: "182 KB",
    sha256: "9f2a · c41d · 0b7e",
    license: "MIT",
    compatibility: "React 18+ · TypeScript 5.x",
    themeCapability: "Light · Dark",
    showcases: ["Workspace", "Editorial"]
  },
  {
    id: "signal-launch",
    slug: "signal-launch",
    route: "web/next/shadcn/signal-launch",
    name: { zh: "Signal Product Launch", en: "Signal Product Launch" },
    family: "Signal Canvas",
    type: "launch",
    accent: "coral",
    author: { name: { zh: "林澄", en: "Lin Chen" }, initials: "LC" },
    summary: {
      zh: "直接、鲜明的产品叙事，用强对比建立行动层级。",
      en: "A direct product story with clear action hierarchy and sharp contrast."
    },
    categories: ["landing", "components"],
    platform: "Web",
    framework: "next",
    frameworkLabel: "Next.js",
    library: "shadcn/ui",
    latestVersion: "0.1.0",
    pinnedVersion: "0.1.0-preview",
    views: 20400,
    likes: 1900,
    updated: 3,
    tags: ["Web", "Next.js", "shadcn/ui", "Light"],
    components: ["Button", "Navigation", "Card", "Accordion", "Marquee", "Dialog"],
    tokens: [
      ["Canvas", "warm / 50"],
      ["Primary", "coral / 500"],
      ["Radius", "6px max"],
      ["Type", "Noto Sans"]
    ],
    buildTool: "Next.js",
    packageManager: "pnpm",
    artifactSize: "214 KB",
    sha256: "1d7c · 9a30 · f52b",
    license: "MIT",
    compatibility: "Next.js 14+ · React 18+",
    themeCapability: "Light · Dark",
    showcases: ["Launch", "Pricing"]
  },
  {
    id: "quiet-publication",
    slug: "grid-publication",
    route: "web/react/shadcn/grid-publication",
    name: { zh: "Grid Knowledge Publication", en: "Grid Knowledge Publication" },
    family: "Quiet Grid",
    type: "publication",
    accent: "blue",
    author: { name: { zh: "Noa Rivera", en: "Noa Rivera" }, initials: "NR" },
    summary: {
      zh: "具有编辑感的知识内容与长文阅读页面。",
      en: "An editorial system for knowledge content and long-form reading."
    },
    categories: ["content", "landing"],
    platform: "Web",
    framework: "react",
    frameworkLabel: "React",
    library: "shadcn/ui",
    latestVersion: "0.1.0",
    pinnedVersion: "0.1.0-preview",
    views: 7400,
    likes: 618,
    updated: 2,
    tags: ["Web", "React", "shadcn/ui", "Light"],
    components: ["Typography", "Breadcrumb", "TableOfContents", "Card", "Tabs"],
    tokens: [
      ["Canvas", "paper / 50"],
      ["Primary", "ink / 900"],
      ["Radius", "4px max"],
      ["Type", "Noto Sans"]
    ],
    buildTool: "Vite",
    packageManager: "pnpm",
    artifactSize: "156 KB",
    sha256: "4b8e · 2c19 · a7d3",
    license: "MIT",
    compatibility: "React 18+ · TypeScript 5.x",
    themeCapability: "Light · Sepia",
    showcases: ["Article", "Archive"]
  },
  {
    id: "signal-notes",
    slug: "signal-notes",
    route: "web/next/shadcn/signal-notes",
    name: { zh: "Signal Creative Field Notes", en: "Signal Creative Field Notes" },
    family: "Signal Canvas",
    type: "notes",
    accent: "",
    author: { name: { zh: "UIDevTpl 团队", en: "UIDevTpl Studio" }, initials: "UI" },
    summary: {
      zh: "带有海报气质的内容体验，适合作品与创意叙事。",
      en: "A poster-like content experience for portfolios and creative stories."
    },
    categories: ["apps", "dashboards", "content"],
    platform: "Web",
    framework: "next",
    frameworkLabel: "Next.js",
    library: "shadcn/ui",
    latestVersion: "0.1.0",
    pinnedVersion: "0.1.0-preview",
    views: 9300,
    likes: 804,
    updated: 1,
    tags: ["Web", "Next.js", "shadcn/ui", "Dark"],
    components: ["Navigation", "Tabs", "AspectRatio", "Card", "HoverCard"],
    tokens: [
      ["Canvas", "ink / 900"],
      ["Primary", "signal / lime"],
      ["Radius", "6px max"],
      ["Type", "Noto Sans"]
    ],
    buildTool: "Next.js",
    packageManager: "pnpm",
    artifactSize: "198 KB",
    sha256: "c0a3 · 6ef1 · 48b9",
    license: "MIT",
    compatibility: "Next.js 14+ · React 18+",
    themeCapability: "Dark · Light",
    showcases: ["Journal", "Gallery"]
  }
];

const copy = {
  zh: {
    brandTagline: "Interface systems for AI",
    navLibrary: "模板库",
    navCategories: "分类",
    navGuide: "使用指南",
    search: "搜索模板",
    searchHint: "名称、技术栈或用途",
    submit: "分享模板",
    language: "中 / EN",
    login: "登录",
    menu: "菜单",
    themeLight: "深色",
    footerNote: "布局原型 · 功能位置可操作 · 正式实现迁移到 Next.js + shadcn/ui",

    homeEyebrow: "UIDEVTPL / SIGNAL DESK",
    homeTitle: "从一套真实界面系统开始。",
    homeBody: "先看清页面、组件和技术边界，再把固定版本交给 AI 迁移到你的项目。",
    homeSearchPlaceholder: "搜索模板、技术栈或用途",
    homeSearchAction: "查找",
    metricPublic: "公开系统",
    metricStacks: "技术组合",
    metricRelease: "当前发布",
    featured: "精选系统",
    previewReady: "可预览",
    inspect: "检查系统",
    copyAi: "复制给 AI",
    intentEyebrow: "01 / 用途索引",
    intentTitle: "你正在构建什么？",
    browseAll: "查看全部用途 →",
    systemsEyebrow: "02 / 最新系统",
    systemsTitle: "最近加入的系统",
    openLibrary: "打开模板库 →",
    openLibraryCard: "在模板库查看全部",
    handoffEyebrow: "03 / 交接",
    handoffTitle: "看完之后，交给 AI 继续。",
    handoffBody: "固定版本、校验值和迁移指令会跟着同一套系统走进你的项目。",
    readGuide: "阅读迁移指南",

    libraryEyebrow: "UIDEVTPL / 模板库",
    libraryTitle: "模板库",
    libraryBody: "按用途、技术栈和版本状态找到可以直接交给 AI 的界面系统。",
    filterTitle: "筛选",
    clear: "清除",
    filterClose: "关闭",
    keyword: "关键词",
    keywordPlaceholder: "名称或 ID",
    fIntent: "用途",
    fPlatform: "平台",
    fFramework: "框架",
    fLibrary: "组件库",
    sort: "排序",
    sortPopular: "热度",
    sortNewest: "最新",
    sortName: "名称",
    all: "全部",
    resultAll: "全部系统",
    previewReadyVersions: "可预览版本",
    emptyTitle: "没有匹配的系统",
    emptyBody: "换个关键词或清除筛选，继续浏览目录。",
    backToAll: "返回全部模板",

    categoriesEyebrow: "UIDEVTPL / 用途目录",
    categoriesTitle: "按你要构建的东西找系统。",
    categoriesBody: "用途只帮助你找到起点，不改变模板自身的固定身份。",
    categoryLatest: "最近更新",
    categoryCount: "系统",

    detailInspect: "SYSTEM INSPECTOR",
    detailPreview: "SHOWCASE",
    detailCheck: "版本检查",
    openPreview: "打开独立预览",
    componentLab: "组件实验室",
    crumbHome: "模板库",
    pinnedVersion: "固定版本",
    checkVersion: "固定版本",
    checkBuild: "构建工具",
    checkPkg: "包管理器",
    checkSize: "产物大小",
    checkSha: "SHA-256",
    checkLicense: "许可证",
    checkCompat: "兼容性",
    checkTheme: "主题能力",
    showcaseTab: "Showcase",
    componentsTab: "组件",
    tokensTab: "Tokens",
    migrationTab: "迁移",
    previewReady2: "就绪",
    previewLoading: "加载中",
    previewError: "错误",
    inspectSummary: "检查真实页面、组件边界和固定版本信息。",
    componentSummary: "这套系统按原子、组合和页面骨架组织。组件实验室会在独立预览里打开。",
    tokenSummary: "这些是迁移时需要保持一致的基础规则。",
    migrationSummary: "把固定版本源码交给 AI，保留参考目录并报告验证结果。",
    fingerprintNote: "复制指令会把固定版本指纹一起带给 AI，迁移前先校验产物。",

    guideEyebrow: "UIDEVTPL / 迁移指南",
    guideTitle: "把一套系统交给 AI。",
    guideBody: "迁移指令负责固定版本、校验源码并把参考目录留在你的项目里。",
    guideCopy: "复制示例指令",
    step1Title: "确认当前项目",
    step1Body: "让 AI 先读取项目目录、规则、技术栈、包管理器和现有改动。",
    step2Title: "下载并校验",
    step2Body: "使用固定版本地址下载模板包，校验 SHA-256 后再继续。",
    step3Title: "保留参考源码",
    step3Body: "将完整模板保存到 .uidevtpl/，不要直接覆盖现有业务文件。",
    step4Title: "迁移并运行门禁",
    step4Body: "迁移 tokens、组件和页面骨架，运行项目已有的格式化、测试和构建。",
    step2Fail: "校验失败时立即停止，不要继续迁移。",
    guideCallout: "正式站会把这里接成固定版本详情页的迁移页签，不会在网站内直接修改你的项目。",

    reservedEyebrow: "UIDEVTPL / 能力预留",
    reservedStatus: "能力尚未开放",
    reservedLoginTitle: "登录",
    reservedSignupTitle: "注册",
    reservedSubmitTitle: "投稿",
    reservedLoginBody: "账号系统在后续版本开放。现在可以直接浏览模板库、检查系统并复制迁移指令。",
    reservedSignupBody: "注册入口保留为产品契约，正式能力上线前不会收集任何账号信息。",
    reservedSubmitBody: "投稿流程在后续版本开放。准备好模板后，可以先参考模板规范文档。",
    reservedGotoLogin: "去登录",
    reservedGotoSignup: "去注册",
    reservedGotoSubmit: "去投稿",
    backToLibrary: "返回模板库",

    searchDialogTitle: "查找一个界面系统",
    searchDialogHint: "输入关键词后回车进入模板库；点击结果直接打开详情。",

    copyDone: "迁移指令已复制，可以交给 AI。",
    copiedFallback: "指令已生成，当前浏览器不支持自动写入剪贴板。",
    reserved: "这是预留入口，正式能力将在后续版本开放。",
    previewErrorHint: "预览加载失败。可以打开独立预览重试。",
    updatedDays: (n) => `${n} 天前更新`
  },
  en: {
    brandTagline: "Interface systems for AI",
    navLibrary: "Library",
    navCategories: "Intents",
    navGuide: "Guide",
    search: "Search templates",
    searchHint: "Name, stack, or intent",
    submit: "Share a system",
    language: "中文 / EN",
    login: "Log in",
    menu: "Menu",
    themeLight: "Dark",
    footerNote: "Layout prototype · interactive locations · migrate to Next.js + shadcn/ui",

    homeEyebrow: "UIDEVTPL / SIGNAL DESK",
    homeTitle: "Start from a real interface system.",
    homeBody: "See the pages, components, and technical boundaries first, then hand the pinned version to AI.",
    homeSearchPlaceholder: "Search templates, stacks, or intents",
    homeSearchAction: "Search",
    metricPublic: "public systems",
    metricStacks: "stack options",
    metricRelease: "current release",
    featured: "Featured system",
    previewReady: "Preview ready",
    inspect: "Inspect system",
    copyAi: "Copy for AI",
    intentEyebrow: "01 / INTENT INDEX",
    intentTitle: "What are you building?",
    browseAll: "Browse all intents →",
    systemsEyebrow: "02 / LATEST SYSTEMS",
    systemsTitle: "Recently added systems",
    openLibrary: "Open library →",
    openLibraryCard: "Browse all in the library",
    handoffEyebrow: "03 / HANDOFF",
    handoffTitle: "Then hand it to AI.",
    handoffBody: "The pinned version, checksum, and migration instruction travel with the same system into your project.",
    readGuide: "Read the handoff guide",

    libraryEyebrow: "UIDEVTPL / LIBRARY",
    libraryTitle: "Library",
    libraryBody: "Find an interface system ready to hand to AI by intent, stack, and version status.",
    filterTitle: "Filters",
    clear: "Clear",
    filterClose: "Close",
    keyword: "Keyword",
    keywordPlaceholder: "Name or ID",
    fIntent: "Intent",
    fPlatform: "Platform",
    fFramework: "Framework",
    fLibrary: "UI library",
    sort: "Sort",
    sortPopular: "Popular",
    sortNewest: "Newest",
    sortName: "Name",
    all: "All",
    resultAll: "All systems",
    previewReadyVersions: "Preview-ready versions",
    emptyTitle: "No matching systems",
    emptyBody: "Try another keyword or clear the filters to keep browsing.",
    backToAll: "Back to all templates",

    categoriesEyebrow: "UIDEVTPL / INTENT DIRECTORY",
    categoriesTitle: "Find a system by what you are building.",
    categoriesBody: "Intents only help you find a starting point. They never change a template's fixed identity.",
    categoryLatest: "Latest",
    categoryCount: "systems",

    detailInspect: "SYSTEM INSPECTOR",
    detailPreview: "SHOWCASE",
    detailCheck: "Version check",
    openPreview: "Open standalone preview",
    componentLab: "Component lab",
    crumbHome: "Library",
    pinnedVersion: "Pinned version",
    checkVersion: "Pinned version",
    checkBuild: "Build tool",
    checkPkg: "Package manager",
    checkSize: "Artifact size",
    checkSha: "SHA-256",
    checkLicense: "License",
    checkCompat: "Compatibility",
    checkTheme: "Theme capability",
    showcaseTab: "Showcase",
    componentsTab: "Components",
    tokensTab: "Tokens",
    migrationTab: "Migration",
    previewReady2: "Ready",
    previewLoading: "Loading",
    previewError: "Error",
    inspectSummary: "Inspect the real page, component boundary, and pinned version.",
    componentSummary: "This system is organized into primitives, compositions, and page skeletons. The component lab opens in the standalone preview.",
    tokenSummary: "Foundations to keep consistent during migration.",
    migrationSummary: "Hand the pinned source to AI, preserve the reference directory, and report verification.",
    fingerprintNote: "The copied instruction carries the pinned-version fingerprint to AI. Verify the artifact before migrating.",

    guideEyebrow: "UIDEVTPL / HANDOFF GUIDE",
    guideTitle: "Hand a system to AI.",
    guideBody: "The migration instruction pins the version, verifies the source, and keeps a reference directory in your project.",
    guideCopy: "Copy sample instruction",
    step1Title: "Confirm the current project",
    step1Body: "Let AI read the project directory, rules, stack, package manager, and existing changes first.",
    step2Title: "Download and verify",
    step2Body: "Download the template artifact from the pinned version address and verify its SHA-256 before continuing.",
    step3Title: "Keep the reference source",
    step3Body: "Save the full template into .uidevtpl/. Do not overwrite existing business files.",
    step4Title: "Migrate and run gates",
    step4Body: "Migrate tokens, components, and page skeletons, then run the project's formatting, tests, and build.",
    step2Fail: "Stop immediately if verification fails. Do not continue the migration.",
    guideCallout: "The production site will wire this to the fixed-version detail migration tab. It will never edit your project from inside the site.",

    reservedEyebrow: "UIDEVTPL / RESERVED",
    reservedStatus: "Capability not open yet",
    reservedLoginTitle: "Log in",
    reservedSignupTitle: "Sign up",
    reservedSubmitTitle: "Submit",
    reservedLoginBody: "Accounts open in a later release. You can already browse the library, inspect systems, and copy migration instructions.",
    reservedSignupBody: "The sign-up entry is kept as a product contract. Until the capability ships, no account information is collected.",
    reservedSubmitBody: "The submission flow opens in a later release. Once your template is ready, start from the template spec.",
    reservedGotoLogin: "Go to log in",
    reservedGotoSignup: "Go to sign up",
    reservedGotoSubmit: "Go to submit",
    backToLibrary: "Back to library",

    searchDialogTitle: "Find an interface system",
    searchDialogHint: "Press Enter on a keyword to open the library. Click a result to open its detail.",

    copyDone: "Migration instruction copied. Hand it to your AI tool.",
    copiedFallback: "The instruction is ready, but this browser cannot write to the clipboard automatically.",
    reserved: "This is a reserved entry. The production capability will open in a later release.",
    previewErrorHint: "Preview failed to load. Retry from the standalone preview.",
    updatedDays: (n) => `updated ${n}d ago`
  }
};
